### ISSUE TITLE
Change language away from "them"

### ISSUE THREAD

**Issue by mattstauffer** [jackmcdade/ppp#1]
Hey bud, would you mind if I made a PR that changed the language a bit? "Them" can feel a bit weird.. I asked around Tighten and @sbine had these ideas for replacements:

"What does this cost there" instead of "What does this cost them"

and 

"To them $100 feels more like $208.77
To make it fair you could charge $47.90"

would be

"In the Phillipines $100 feels more like $208.77
To make it fair you could charge $47.90"

What do you think if I PR that?

**Comment by jackmcdade** [comment]
For sure! Would happily merge that. :)
